"""empty message

Revision ID: bfcae76ea3fb
Revises: 
Create Date: 2021-03-09 16:00:43.793868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcae76ea3fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('concept_name', sa.String(length=256), nullable=True),
    sa.Column('domain_id', sa.String(length=32), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=32), nullable=False),
    sa.Column('concept_class_id', sa.String(length=32), nullable=False),
    sa.Column('standard_concept', sa.String(length=64), nullable=True),
    sa.Column('concept_code', sa.String(length=64), nullable=False),
    sa.Column('valid_start_date', sa.Date(), nullable=False),
    sa.Column('valid_end_date', sa.Date(), nullable=False),
    sa.Column('invalid_reason', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('concept_id')
    )
    op.create_table('person',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('gender_concept_id', sa.Integer(), nullable=False),
    sa.Column('birth_datetime', sa.DateTime(), nullable=False),
    sa.Column('race_concept_id', sa.Integer(), nullable=False),
    sa.Column('ethnicity_concept_id', sa.Integer(), nullable=False),
    sa.Column('year_of_birth', sa.Integer(), nullable=False),
    sa.Column('month_of_birth', sa.Integer(), nullable=False),
    sa.Column('day_of_birth', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('care_site_id', sa.Integer(), nullable=True),
    sa.Column('person_source_value', sa.String(length=64), nullable=False),
    sa.Column('gender_source_value', sa.String(length=4), nullable=False),
    sa.Column('gender_source_concept_id', sa.Integer(), nullable=True),
    sa.Column('race_source_value', sa.String(length=32), nullable=False),
    sa.Column('race_source_concept_id', sa.Integer(), nullable=True),
    sa.Column('ethnicity_source_value', sa.String(length=32), nullable=False),
    sa.Column('ethnicity_source_concept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ethnicity_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gender_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gender_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('death',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('death_date', sa.Date(), nullable=False),
    sa.Column('death_datetime', sa.DateTime(), nullable=True),
    sa.Column('death_type_concept_id', sa.Integer(), nullable=False),
    sa.Column('cause_concept_id', sa.Integer(), nullable=True),
    sa.Column('cause_source_value', sa.String(length=64), nullable=False),
    sa.Column('cause_source_concept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cause_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['death_type_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('visit_occurrence',
    sa.Column('visit_occurrence_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('visit_concept_id', sa.Integer(), nullable=False),
    sa.Column('visit_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('visit_end_datetime', sa.DateTime(), nullable=False),
    sa.Column('visit_start_date', sa.Date(), nullable=False),
    sa.Column('visit_end_date', sa.Date(), nullable=False),
    sa.Column('visit_type_concept_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('care_site_id', sa.Integer(), nullable=True),
    sa.Column('visit_source_value', sa.String(length=64), nullable=False),
    sa.Column('visit_source_concept_id', sa.Integer(), nullable=True),
    sa.Column('admitting_source_concept_id', sa.Integer(), nullable=True),
    sa.Column('admitting_source_value', sa.String(length=64), nullable=True),
    sa.Column('discharge_to_concept_id', sa.Integer(), nullable=True),
    sa.Column('discharge_to_source_value', sa.String(length=64), nullable=True),
    sa.Column('preceding_visit_concept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admitting_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discharge_to_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preceding_visit_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_type_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_occurrence_id')
    )
    op.create_table('condition_occurrence',
    sa.Column('condition_occurrence_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('visit_occurrence_id', sa.Integer(), nullable=False),
    sa.Column('condition_concept_id', sa.Integer(), nullable=True),
    sa.Column('condition_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('condition_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('condition_start_date', sa.Date(), nullable=False),
    sa.Column('condition_end_date', sa.Date(), nullable=True),
    sa.Column('condition_type_concept_id', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('visit_detail_id', sa.Integer(), nullable=False),
    sa.Column('condition_source_value', sa.String(length=64), nullable=False),
    sa.Column('condition_source_concept_id', sa.Integer(), nullable=True),
    sa.Column('condition_status_source_value', sa.String(length=64), nullable=True),
    sa.Column('condition_status_concept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_status_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_type_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_occurrence_id'], ['visit_occurrence.visit_occurrence_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('condition_occurrence_id')
    )
    op.create_table('drug_exposure',
    sa.Column('drug_exposure_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('drug_concept_id', sa.Integer(), nullable=True),
    sa.Column('drug_exposure_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('drug_exposure_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('visit_occurrence_id', sa.Integer(), nullable=False),
    sa.Column('drug_exposure_start_date', sa.Date(), nullable=False),
    sa.Column('drug_exposure_end_date', sa.Date(), nullable=False),
    sa.Column('verbatim_end_date', sa.Date(), nullable=True),
    sa.Column('drug_type_concept_id', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('refills', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('days_supply', sa.Integer(), nullable=False),
    sa.Column('sig', sa.String(length=64), nullable=True),
    sa.Column('route_concept_id', sa.Integer(), nullable=True),
    sa.Column('lot_number', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('drug_source_value', sa.String(length=32), nullable=False),
    sa.Column('drug_source_concept_id', sa.Integer(), nullable=True),
    sa.Column('route_source_value', sa.String(length=64), nullable=True),
    sa.Column('does_unit_source_value', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['drug_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_source_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_type_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_concept_id'], ['concept.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_occurrence_id'], ['visit_occurrence.visit_occurrence_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drug_exposure_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drug_exposure')
    op.drop_table('condition_occurrence')
    op.drop_table('visit_occurrence')
    op.drop_table('death')
    op.drop_table('person')
    op.drop_table('concept')
    # ### end Alembic commands ###
